name: Build Unsigned IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make temporary Xcode project
        run: |
          mkdir temp_project
          cd temp_project
          xcodebuild -create-xcodeproj temp.xcodeproj
          cd ..

      - name: Copy Swift files
        run: |
          cp -R MusicPlayer/*.swift temp_project/

      - name: Build unsigned IPA
        run: |
          cd temp_project
          xcodebuild \
            -project temp.xcodeproj \
            -scheme temp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/temp.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            archive
          xcodebuild -exportArchive \
            -archivePath $PWD/build/temp.xcarchive \
            -exportOptionsPlist ../ExportOptions.plist \
            -exportPath $PWD/build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: temp_project/build/*.ipa
